# Generated by Django 5.1 on 2024-09-02 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcms', '0001_initial'),
        ('subcategorias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategoria',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='appcms.categoria'),
        ),
    ]
