# Generated by Django 5.1 on 2024-09-02 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subcategorias', '0002_alter_subcategoria_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategoria',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
