# Generated by Django 5.1 on 2024-09-20 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenido',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
