# Generated by Django 5.1 on 2024-09-13 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenidos', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contenido',
        ),
    ]
