# Generated by Django 5.1 on 2024-09-12 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenidos', '0002_delete_contenido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Blog', 'Blog'), ('Multimedia', 'Multimedia')], max_length=10)),
                ('estado', models.CharField(choices=[('Borrador', 'Borrador'), ('Revisión', 'Revisión'), ('A Publicar', 'A Publicar'), ('Publicado', 'Publicado'), ('Inactivo', 'Inactivo')], default='Borrador', max_length=20)),
                ('titulo', models.CharField(max_length=255)),
                ('texto', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='multimedia/')),
                ('imagen_url', models.URLField(blank=True, null=True)),
                ('id_historial_mod', models.IntegerField(blank=True, null=True)),
                ('publicador_id', models.CharField(blank=True, max_length=255, null=True)),
                ('autor_id', models.CharField(blank=True, max_length=255, null=True)),
                ('editor_id', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contenidos', to='contenidos.categoria')),
                ('subcategoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcontenidos', to='contenidos.categoria')),
            ],
            options={
                'verbose_name_plural': 'Contenidos',
                'db_table': 'contenidos_contenido',
            },
        ),
    ]
