# Generated by Django 5.1 on 2024-09-27 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenidos', '0002_comentario'),
        ('contenidos', '0002_contenido_fecha_modificacion'),
    ]

    operations = [
    ]
