# Generated by Django 5.1.1 on 2024-10-05 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenidos', '0003_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='usuario',
            field=models.CharField(max_length=255),
        ),
    ]
