# Generated by Django 5.1 on 2024-09-13 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenidos', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contenido',
            table=None,
        ),
    ]
