# Generated by Django 5.1 on 2024-09-13 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenidos', '0004_alter_contenido_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contenido',
        ),
    ]
