# Generated by Django 5.1 on 2024-10-25 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenidos', '0004_alter_comentario_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComentarioRoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_remitente', models.CharField(max_length=255)),
                ('usuario_receptor', models.CharField(max_length=255)),
                ('comentario', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
                ('contenido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_Roles', to='contenidos.contenido')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
