# Generated by Django 5.1 on 2024-10-25 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenidos', '0005_comentarioroles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentarioroles',
            old_name='usuario_receptor',
            new_name='usuario',
        ),
        migrations.RemoveField(
            model_name='comentarioroles',
            name='usuario_remitente',
        ),
    ]
