# Generated by Django 5.1 on 2024-10-31 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenidos', '0006_rename_usuario_receptor_comentarioroles_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenido',
            name='nro_me_gusta',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contenido',
            name='nro_visualizaciones',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
