# Generated by Django 5.1 on 2024-10-31 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenidos', '0007_contenido_nro_me_gusta_contenido_nro_visualizaciones'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contenido',
            old_name='nro_me_gusta',
            new_name='megusta',
        ),
        migrations.RenameField(
            model_name='contenido',
            old_name='nro_visualizaciones',
            new_name='visualizaciones',
        ),
    ]
