# Generated by Django 5.1 on 2024-11-22 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenidos', '0009_visualizacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('usuario', models.CharField(max_length=255)),
                ('accion', models.CharField(choices=[('CREADO', 'CREADO'), ('EDITADO', 'EDITADO'), ('ELIMINADO', 'ELIMINADO'), ('PUBLICADO', 'PUBLICADO'), ('ENVIADO A BORRADOR', 'ENVIADO A BORRADOR'), ('ENVIADO A PUBLICAR', 'ENVIADO A PUBLICAR'), ('ENVIADO A EDICION', 'ENVIADO A EDICION')], max_length=50)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Histórico de Contenido',
                'verbose_name_plural': 'Históricos de Contenidos',
                'ordering': ['-fecha'],
            },
        ),
    ]
