# Generated by Django 5.1 on 2024-09-16 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appcms', '0002_contenido'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contenido',
        ),
    ]
