# Generated by Django 5.1 on 2024-08-30 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appcms', '0002_subcategoria'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subcategoria',
        ),
    ]
